In [1]:
import pandas as pd

stores = pd.read_csv("../data/raw/starbucks_stores_raw.csv")

stores.shape
stores.head()
stores.info()
stores.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 25600 entries, 0 to 25599
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      25600 non-null  str
 1   StarbucksId             25600 non-null  int64
 2   Name                    25600 non-null  str
 3   BrandName               25600 non-null  str
 4   StoreNumber             25600 non-null  str
 5   PhoneNumber             18739 non-null  str
 6   OwnershipType           25600 non-null  str
 7   Street1                 25596 non-null  str
 8   Street2                 8424 non-null   str
 9   Street3                 5732 non-null   str
 10  City                    25585 non-null  str
 11  CountrySubdivisionCode  25600 non-null  str
 12  CountryCode             25600 non-null  str
 13  PostalCode              24078 non-null  str
 14  Longitude               25599 non-null  float64
 15  Latitude                25599 non-null  float64
 16  TimezoneOffset          25600 non-null  int64
 17  TimezoneId              25600 non-null  str
 18  TimezoneOlsonId         25600 non-null  str
 19  FirstSeen               25600 non-null  str
 20  LastSeen                25600 non-null  str
dtypes: float64(2), int64(2), str(17)
memory usage: 4.1 MB

Id                            0
StarbucksId                   0
Name                          0
BrandName                     0
StoreNumber                   0
PhoneNumber                6861
OwnershipType                 0
Street1                       4
Street2                   17176
Street3                   19868
City                         15
CountrySubdivisionCode        0
CountryCode                   0
PostalCode                 1522
Longitude                     1
Latitude                      1
TimezoneOffset                0
TimezoneId                    0
TimezoneOlsonId               0
FirstSeen                     0
LastSeen                      0
dtype: int64

In [2]:
keep_cols = ["StarbucksId", "Name", "OwnershipType",
             "CountrySubdivisionCode", "CountryCode", "Longitude", "Latitude"]
stores = stores[keep_cols]

In [3]:
stores.shape        
stores.head()

,StarbucksId,Name,OwnershipType,CountrySubdivisionCode,CountryCode,Longitude,Latitude
0,10357,Target Virginia T-847,LS,MN,US,-92.55,47.51
1,6557,PDX A 2,LS,OR,US,-122.59,45.59
2,1010600,235 Bourke Street,LS,VIC,AU,144.97,-37.81
3,1014921,Oasis Al-Kharj,LS,01,SA,47.27,24.13
4,14667,Target Trumbull T-1956,LS,CT,US,-73.15,41.23

In [4]:
stores = stores.rename(columns={
    "StarbucksId": "store_id",
    "Name": "store_name",
    "OwnershipType": "ownership_type",
    "CountrySubdivisionCode": "state_region",
    "CountryCode": "country_code",
    "Longitude": "longitude",
    "Latitude": "latitude",
})
stores.columns.tolist()

['store_id',
 'store_name',
 'ownership_type',
 'state_region',
 'country_code',
 'longitude',
 'latitude']

In [5]:
# how many distinct country codes, and what are they?
stores["country_code"].nunique()
stores["country_code"].unique()

<StringArray>
['US', 'AU', 'SA', 'CN', 'KR', 'GB', 'FR', 'MX', 'TH', 'DE', 'PH', 'CA', 'JP',
 'TW', 'PT', 'KW', 'MY', 'ID', 'CL', 'LU', 'SG', 'TR', 'AR', 'ES', 'BE', 'BG',
 'MA', 'RU', 'CR', 'CZ', 'AE', 'ZA', 'IN', 'PE', 'CH', 'PL', 'EG', 'IE', 'BR',
 'AT', 'PR', 'LB', 'NZ', 'GR', 'CO', 'QA', 'SE', 'RO', 'HU', 'KZ', 'NL', 'OM',
 'CW', 'DK', 'JO', 'BS', 'NO', 'CY', 'SV', 'AZ', 'GT', 'FI', 'PA', 'AD', 'VN',
 'BN', 'SK', 'BH', 'KH', 'BO', 'AW', 'TT', 'MC']
Length: 73, dtype: str

In [6]:
stores.columns.tolist()   # should be 7 columns, no 'city'
stores.shape              # (25600, 7)

(25600, 7)

In [7]:
stores.duplicated().sum()

np.int64(0)

verified no duplicate stores; store_id confirmed unique across all 25,600 rows

In [8]:
stores["store_id"].duplicated().sum()

np.int64(0)

In [9]:
stores[stores["latitude"].isna()]

,store_id,store_name,ownership_type,state_region,country_code,longitude,latitude
4393,113833,Yoido IFC Mall - 1F,JV,11,KR,NaN,NaN

In [11]:
ownership_map = {
    "CO": "Company Owned",
    "LS": "Licensed Store",
    "JV": "Joint Venture",
    "FR": "Franchise"
}
stores["ownership_type"] = stores["ownership_type"].map(ownership_map)

In [10]:
stores.info()
print(stores.isna().sum())
print(stores.shape)

<class 'pandas.DataFrame'>
RangeIndex: 25600 entries, 0 to 25599
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   store_id        25600 non-null  int64
 1   store_name      25600 non-null  str
 2   ownership_type  25600 non-null  str
 3   state_region    25600 non-null  str
 4   country_code    25600 non-null  str
 5   longitude       25599 non-null  float64
 6   latitude        25599 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 1.4 MB
store_id          0
store_name        0
ownership_type    0
state_region      0
country_code      0
longitude         1
latitude          1
dtype: int64
(25600, 7)

In [25]:
stores.to_csv("../data/cleaned/stores_clean.csv", index=False)

check_stores = pd.read_csv("../data/cleaned/stores_clean.csv")
check_stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 25600 entries, 0 to 25599
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   store_id        25600 non-null  int64
 1   store_name      25600 non-null  str
 2   ownership_type  25600 non-null  str
 3   state_region    25600 non-null  str
 4   country_code    25600 non-null  str
 5   longitude       25599 non-null  float64
 6   latitude        25599 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 1.4 MB